# Generated by Django 3.0.6 on 2022-04-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabFingerprintTb',
            fields=[
                ('finger_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Lab_fingerprint_tb',
                'managed': False,
            },
        ),
    ]
