# Generated by Django 3.0.6 on 2022-04-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_labfingerprinttb'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabAttendanceInfo',
            fields=[
                ('student_id', models.IntegerField()),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('staytime', models.IntegerField(blank=True, db_column='Staytime', null=True)),
                ('info_count', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Lab_attendance_info',
                'managed': False,
            },
        ),
    ]
