# Generated by Django 3.0.6 on 2022-04-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_labattendanceinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterInfo',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('enter_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'enter_info',
                'managed': False,
            },
        ),
    ]
