# Generated by Django 3.0.6 on 2022-05-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_enterinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTips',
            fields=[
                ('sentence', models.TextField(blank=True, db_column='Sentence', null=True)),
                ('image', models.CharField(blank=True, db_column='Image', max_length=100, null=True)),
                ('num', models.AutoField(db_column='Num', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Lab_tips',
                'managed': False,
            },
        ),
    ]
