# Generated by Django 3.0.6 on 2022-05-24 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_labtips'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnterInfo',
        ),
        migrations.DeleteModel(
            name='LabAttendanceInfo',
        ),
    ]
