# Generated by Django 3.0.6 on 2022-05-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20220524_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('enter_time', models.TimeField(blank=True, null=True)),
                ('staytime', models.IntegerField(blank=True, null=True)),
                ('count', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Lab_report',
                'managed': False,
            },
        ),
    ]
